name: Update NLP Engine Files

on:
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2

    - name: Get latest release info from VisualText/nlp-engine
      id: get_release
      uses: actions/github-script@v6
      with:
        script: |
          const latestRelease = await github.rest.repos.getLatestRelease({
            owner: 'VisualText',
            repo: 'nlp-engine'
          });
          const tag_name = latestRelease.data.tag_name,
          const assets = latestRelease.data.assets.map(asset => asset.browser_download_url);
          console.log(`assets: ${assets}`);
  
    - name: Download release assets
      run: |
        mkdir -p release-assets
        for asset in ${{ steps.get_release.outputs.assets }}; do
          if [[ $asset == *"libicutu.a" || $asset == *"libicuuc.a" || $asset == *"nlpl.exe" || $asset == *"nlpengine.zip" ]]; then
          wget -P release-assets $asset
          fi
        done

    - name: List runner workspace
      run: find $RUNNER_WORKSPACE
      shell: bash

    - name: rename nlpl.exe to nlp.exe
      run: mv release-assets/nlpl.exe release-assets/nlp.exe
      
    - name: Unzip the nlpengine.zip
      run: |
        unzip release-assets/nlpengine.zip -d release-assets

    - name: Copy assets to repository
      run: |
        cp -r release-assets/* .

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update NLP Engine files to latest release ${{ steps.get_release.outputs.tag_name }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag this repository with the latest release version
      run: |
        git tag ${{ steps.get_release.outputs.tag_name }}
        git push origin ${{ steps.get_release.outputs.tag_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
